from stnu.java_comparison.stnu_to_xml_function import stnu_to_xml
from classes.stnu import STNU

# Example Hunsberger slide 118 (controllable)
stnu = STNU()
stnu.add_node('A')
stnu.add_node('B')
stnu.add_node('C')
stnu.set_ordinary_edge('B', 'C', 5)
stnu.add_contingent_link('A', 'C', 2, 9)
stnu_to_xml(stnu, "slide118", "stnu/java_comparison/xml_files")

# Test example from paper Hunsberger'23, fig 7a (controllable)
stnu = STNU()
stnu.add_node('A')
stnu.add_node('C')
stnu.add_node('W')
stnu.add_node('X')
stnu.add_node('Y')
stnu.set_ordinary_edge('X', 'C', 3)
stnu.set_ordinary_edge('X', 'Y', -2)
stnu.set_ordinary_edge('Y', 'C', 1)
stnu.set_ordinary_edge('C', 'W', -7)
stnu.add_contingent_link('A', 'C', 1, 10)
stnu_to_xml(stnu, "hunsberger23", "stnu/java_comparison/xml_files")

# Test example from Morris'14 paper
stnu = STNU()
stnu.add_node('A')
stnu.add_node('B')
stnu.add_node('C')
stnu.add_node('D')
stnu.add_node('E')

stnu.set_ordinary_edge('B', 'E', -2)
stnu.set_ordinary_edge('E', 'B', 4)
stnu.set_ordinary_edge('B', 'D', 1)
stnu.set_ordinary_edge('D', 'B', 3)
stnu.add_contingent_link('A', 'B', 0, 2)
stnu.add_contingent_link('C', 'D', 0, 3)
stnu_to_xml(stnu, "morris14", "stnu/java_comparison/xml_files")
